### ISSUE TITLE
Bug target frame

### ISSUE THREAD

**Issue by freesay** [Kkthnx/KkthnxUI_WotLK#10]
Hi! I'm found a bug in the last relise. Target frame does not move. He shifted up.

**Comment by freesay** [comment]
You're doing a very good addon.

**Comment by Kkthnx** [comment]
Could you give me steps to reproduce this?

**Comment by Kkthnx** [comment]
Nvm I see the issue but need to look into what I've changed to mess this up. Thank you for the report.

**Comment by Kkthnx** [comment]
Fixed in commit 52b2348a20bc18442ab34d4e7e718fe9de254eb2

I am closing this.
