### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by freesay** [Kkthnx/KkthnxUI_WotLK#12]
Hi! How can I help you translate addon?

**Comment by Kkthnx** [comment]
Yes! I will add you in credits! Thank you very much!

**Comment by freesay** [comment]
Some options are not translated, and some do not have to localized files.

**Comment by Kkthnx** [comment]
I will get on that. Give me some time. I am currently re-coding the action bars completely so been very busy with that.

**Comment by freesay** [comment]
Fixed minimap button from AthlasLoot. Please =)

**Comment by Kkthnx** [comment]
Idk how well this will go considering it is a Fubar Plugin :D I will look into it.

**Comment by Kkthnx** [comment]
@freesay there is now a Beta branch you can look at. Has the bars redone and some RU you can check. Won't go to live branch for some time. https://github.com/Kkthnx/KkthnxUI_WotLK/tree/Beta

**Comment by freesay** [comment]
It's alright but there is a problem.
1. minimap button to mess.
2. stance bar DK don't move.
3. action bars is cool but they are not applicable darken.
4. make optional choice on/off panel of griffin please. 
http://pixs.ru/showimage/WoWScrnSho_9280385_22062403.jpg

**Comment by freesay** [comment]
Can I make a suggestion?
1. please make the display of health as in the picture
2. you can remove this ugly flicker when resting?
http://pixs.ru/showimage/WoWScrnSho_4848206_22062537.jpg

**Comment by freesay** [comment]
It's perfect. Good job. Fixed minimap buttons, add display current and percent HP, and remove ugly backlight resting =) Will amazing!

**Comment by Kkthnx** [comment]
Mind to share your changes and I can implement them?

**Comment by freesay** [comment]
Sorry, i'm not coding. This painted image. I thought maybe you know how to make it.

**Comment by Kkthnx** [comment]
I am working on the minimap button later today and I already know how to kill of the resting flash texture. You should see a push tonight for it.

**Comment by freesay** [comment]
There is a problem. Id does not show up actionbar in the Icecrown Citadel, to Professor Putricide in Mutated Abomination. It's very bad. Also is happens in Oculus to dragons.

**Comment by Kkthnx** [comment]
@freesay
This is what I am working on currently. Look at the unit frames values!
Google Traslate: это то, что я работаю на данный момент. Посмотрите на значения единичных рам!
![wowscrnshot_052416_212021](https://cloud.githubusercontent.com/assets/1692977/15525149/7d231870-21f5-11e6-87ec-a4bd1e77d05a.jpg)

**Comment by Kkthnx** [comment]
Also action bar issue should be fixed with the new action bars.

**Comment by freesay** [comment]
Yeah! It's cool! Make font macro smaller. 
P/TFrame good! Exactly what is needed!

**Comment by freesay** [comment]
Optionally choice on/off frame of griffin?

**Comment by Kkthnx** [comment]
Well with the new action bars there is no griffins or action bar textures. I might put an option in the for old action bars. Idk.

Ну с новым действием баров нет грифонов или панель действий текстур. Я мог бы поставить опцию в старых баров действий. ИДК.

**Comment by freesay** [comment]
Put it please. They are beautiful.

**Comment by Kkthnx** [comment]
So the minimap buttons are fixed. I just can't figure out how to catch the AtlasLoot minimap button "FuBarPluginAtlasLootFuFrameMinimapButton" :( Might just need to rewrite the module and delay catching the buttons so they all load first then check for them and move and line them up. A good example of this is an addon called Square minimap buttons that does this.

Так кнопки MiniMap фиксированы. Я просто не могу понять, как поймать кнопку AtlasLoot миникарты "FuBarPluginAtlasLootFuFrameMinimapButton" :( Может просто нужно переписать модуль и задержать ловить кнопки таким образом, они все нагрузки сначала тогда проверяют их и двигаться и выровнять их. Хороший пример это аддон называется Square MiniMap кнопки, что делает это.

**Comment by freesay** [comment]
I'm download last beta realise. Good job! =) Very good. 
I did not understand how to move the stance bar.

**Comment by freesay** [comment]
Does not work.
http://i9.pixs.ru/storage/7/1/9/WoWScrnSho_5745568_22087719.jpg

**Comment by Kkthnx** [comment]
![wowscrnshot_052516_205702](https://cloud.githubusercontent.com/assets/1692977/15560615/4df6a186-22bb-11e6-9bd7-56df821317d5.jpg)

**Comment by Kkthnx** [comment]
If you type /moveui and then you will see that you can move the stancebar aka Shapeshift. It will be named ShiftHolder

Если вы введете / moveui, и тогда вы увидите, что вы можете переместить stancebar ака Shapeshift. Он будет называться ShiftHolder

**Comment by freesay** [comment]
How to translate these lines?
How add them to a file ruRU.lua?
http://i9.pixs.ru/storage/9/3/1/SnimokPNG_1783095_22087931.png

**Comment by freesay** [comment]
Notification in the raid does not work.
Notifies only group.

**Comment by Kkthnx** [comment]
I'll setup so you can translate it. 1 second. Also with the issue with announcement in spells I know about that issue but trying to figure it out.

**Comment by Kkthnx** [comment]
Closing this. If you have more issues, just open another tracker. Thanks @freesay
