### ISSUE TITLE
actionbar scaling

### ISSUE THREAD

**Issue by Senshik** [Kkthnx/KkthnxUI_WotLK#20]
Action bar scale option doesn't work at last build.

**Comment by freesay** [comment]
It's work.

**Comment by Kkthnx** [comment]
Best thing to do is reinstall a fresh copy.

**Comment by Senshik** [comment]
![wowscrnshot_052516_231932](https://cloud.githubusercontent.com/assets/19577225/15554983/3de5841a-22cf-11e6-8cbd-7b5e6511a59c.jpg)
![wowscrnshot_052516_231953](https://cloud.githubusercontent.com/assets/19577225/15554985/3e17b386-22cf-11e6-8d90-2ae1a6e26a3f.jpg)
Nothing changing.

**Comment by Kkthnx** [comment]
Once you enter a new value, be sure you hit the yellow OKAY button to the right of the box then hit apply! Let me know.

**Comment by Senshik** [comment]
I'm not stupid, and know about okay button, and hit it.
https://youtu.be/1PRDcZOMBhw

**Comment by Senshik** [comment]
Oh, you already fixed it with new action bars settings. Thanks.
