### ISSUE TITLE
Raid frame.

### ISSUE THREAD

**Issue by freesay** [Kkthnx/KkthnxUI_WotLK#27]
What about raid frame?
Maybe they should do? To really was all in one =)
Something like this: http://i9.pixs.ru/storage/1/7/5/WoWScrnSho_2804731_22111175.jpg
![Image](http://i9.pixs.ru/storage/1/7/5/WoWScrnSho_2804731_22111175.jpg)

**Comment by Kkthnx** [comment]
I really do not think I am going to code raid frames right now. Though that grid setup looks really good. I'll set up a profile for grid so people can install that.

Я действительно не думаю, что я собираюсь код рейдовых кадров прямо сейчас. Хотя эта установка сетки выглядит очень хорошо. Я настроить профиль для сетки, чтобы люди могли установить, что.
