### ISSUE TITLE
Error messages.

### ISSUE THREAD

**Issue by freesay** [Kkthnx/KkthnxUI_WotLK#29]
Annoying message.
![image](http://i11.pixs.ru/storage/9/0/4/WoWScrnSho_6869905_22111904.jpg)

**Comment by Kkthnx** [comment]
I'll add this to the blacklist later today. This is the message you get when you spam too much in chat right?

Я добавлю это в черный список позже сегодня. Это сообщение, которое вы получаете, когда вы слишком много спама в чате права?

**Comment by freesay** [comment]
I do not write anything. This message can be seen permanently in the cities.

**Comment by Kkthnx** [comment]
Oh, you play on WoWCircle huh? Do you happen to have Carbonite addon enabled? I think this is a WoWCircle spam filter of their own maybe.

О, вы играете на WoWCircle да? Вы случайно не включить Карбонитовые аддон? Я думаю, что это WoWCircle спам-фильтр самостоятельно, может быть.

**Comment by Kkthnx** [comment]
This isn't anything from my UI. I looked on WowCircle's forums and seen others have the same issue you are having. Look http://forum.wowcircle.com/showthread.php?t=260044

Это не что-то из моего UI. Я смотрел на форумах WowCircle и видел другие имеют один и тот же вопрос вы имеете. Смотри http://forum.wowcircle.com/showthread.php?t=260044

**Comment by freesay** [comment]
Yes, it is a server problem =(

**Comment by freesay** [comment]
Of the installed add-ons:
KkthnxUI =) 
Recount
Grid
AthlasLoot
