### ISSUE TITLE
SpamageMeters and numeration

### ISSUE THREAD

**Issue by Foximys** [Kkthnx/KkthnxUI_WotLK#30]
KkthnxUI\Modules\Chat\SpamageMeters.lua
at 28 line
	"^Numeration: (.*) - (.*)$", - not work
        
	"^# (.*) - (.*)$",	 -- work 
![wowscrnshot_052816_033014](https://cloud.githubusercontent.com/assets/3339049/15623074/49b0d41e-2489-11e6-96ab-525c876ad7ed.jpg)
but spell in this windows can't click for info:
![wowscrnshot_052816_033039](https://cloud.githubusercontent.com/assets/3339049/15623152/3fc9cef0-248a-11e6-8d3e-56d6d79fec2d.jpg)

**Comment by Kkthnx** [comment]
Fixed in update
https://github.com/Kkthnx/KkthnxUI_WotLK/commit/926c8dd7e9ee0da0a3824fc5075579ea78769a3a

**Comment by Kkthnx** [comment]
If you get time can you try changing line 28 to 

"^Numeration: (.*) for (.*)$",

See if that works?

Если вы получаете время вы можете попытаться изменить линии 28

"^Numeration: (.*) for (.*)$",

Смотрите, если это работает?

**Comment by Foximys** [comment]
nope
![nw](https://cloud.githubusercontent.com/assets/3339049/15625369/8795a690-24bd-11e6-8dab-e86628e2de4b.JPG)
