### ISSUE TITLE
Missing color.

### ISSUE THREAD

**Issue by freesay** [Kkthnx/KkthnxUI_WotLK#31]
![wowscrnshot_052816_003353](https://cloud.githubusercontent.com/assets/19500175/15623527/617316f4-247d-11e6-8a50-fa2cc0c84fd9.jpg)

**Comment by freesay** [comment]
Later it became like this:
![wowscrnshot_052816_025036](https://cloud.githubusercontent.com/assets/19500175/15623656/7a8efe6c-247f-11e6-8d19-db03b8610265.jpg)

**Comment by freesay** [comment]
I made these changes (i, as the tank is very convenient):
`for _, Textures in ipairs({
	"PlayerAttackGlow",
	"PetAttackModeTexture",
	"PlayerRestGlow",
	--"PlayerRestIcon",
	"PlayerStatusGlow",
	"PlayerStatusTexture",
	"PlayerAttackBackground",
	--"PlayerFrameGroupIndicator",
	--"PlayerFrameFlash",
	--"TargetFrameFlash",
	--"FocusFrameFlash",
	--"PetFrameFlash",
	--"PlayerFrameRoleIcon",
	"TargetFrameNumericalThreat",

}) do
	local Texture = _G[Textures]
	if Texture then
		Texture:Hide()
		Texture.Show = K.Dummy
	end
end`

Result:
![wowscrnshot_052816_030200](https://cloud.githubusercontent.com/assets/19500175/15623808/0bb56bd6-2482-11e6-9d0f-fb303ae6c7b4.jpg)

**Comment by Kkthnx** [comment]
Fixed in update
https://github.com/Kkthnx/KkthnxUI_WotLK/commit/926c8dd7e9ee0da0a3824fc5075579ea78769a3a
