### ISSUE TITLE
panels and bg stat

### ISSUE THREAD

**Issue by Foximys** [Kkthnx/KkthnxUI_WotLK#32]
if use "Split the fifth bar on two bars on 6 button" on bg dont see healing stat
![bgstat](https://cloud.githubusercontent.com/assets/3339049/15625380/1ae5baf2-24be-11e6-9bd6-5a6569f8e10c.JPG)

**Comment by Kkthnx** [comment]
I will need to look how to approach this tomorrow. I looked at it a little bit ago but I am unsure as to what to do right now with it.

Мне нужно будет посмотреть, как подойти к этому завтра. Я посмотрел на него немного назад, но я не уверен относительно того, что делать сейчас с ней.

**Comment by Kkthnx** [comment]
Temp fixed in update https://github.com/Kkthnx/KkthnxUI_WotLK/commit/1f19704a97d5b3aeaa8ffcb8db33a6f876d79342
