### ISSUE TITLE
Bank.

### ISSUE THREAD

**Issue by freesay** [Kkthnx/KkthnxUI_WotLK#35]
Please see the bank code. There is a bug with the addition of bags in the slots.

**Comment by Kkthnx** [comment]
Can you explain the issue you are having?

Можете ли вы объяснить этот вопрос вы испытываете?

**Comment by freesay** [comment]
Bag is not inserted into the empty slot.
![wowscrnshot_052816_094554](https://cloud.githubusercontent.com/assets/19500175/15625720/8d557db0-24ba-11e6-8d59-70fa37318a77.jpg)

**Comment by freesay** [comment]
Else add button for keys please =)

**Comment by Kkthnx** [comment]
I totally forgot about keys :( I will get on this asap.

Я совершенно забыл о ключах :( я получу на это как можно скорее.

**Comment by Kkthnx** [comment]
Try dragging the bag in the empty bank bag slot. This works for me.

Попробуйте перетащить мешок в пустой слот банка мешок. Это работает для меня.

**Comment by freesay** [comment]
Very strange. Not one of the seven slots bag is not put. No additional add-ons for the bags and the bank has been established.

**Comment by Kkthnx** [comment]
Yah I see the issue but I need some time to figure this out.

Ях Я вижу этот вопрос , но мне нужно некоторое время , чтобы понять это .

**Comment by Kkthnx** [comment]
Fixed in update
https://github.com/Kkthnx/KkthnxUI_WotLK/commit/686f22d1209c8a22635b5c46bf1b0cb8c15fdbb1
