### ISSUE TITLE
Translate items.

### ISSUE THREAD

**Issue by freesay** [Kkthnx/KkthnxUI_WotLK#36]
Stats of all items have become in English
![wowscrnshot_052916_031838](https://cloud.githubusercontent.com/assets/19500175/15630656/f900efa8-254c-11e6-8d7a-d2fc6238d5d2.jpg)

**Comment by Kkthnx** [comment]
Crap I forgot to setup the globals file for this.

Дерьме я забыл установить глобалов файл для этого.

**Comment by Kkthnx** [comment]
Temp fixed in update 
https://github.com/Kkthnx/KkthnxUI_WotLK/commit/403a636eb8df1de81201605c47bab8bfa97d3a68
