### ISSUE TITLE
Totem bar, loot

### ISSUE THREAD

**Issue by Jolobolo** [Kkthnx/KkthnxUI_WotLK#37]
In last version totem bar disappeared. And u need look at module that respond for loot window, when u open it cursor is on frame of the border and I think it will be better if cursor will be over first item
![image](https://cloud.githubusercontent.com/assets/19752502/15801856/cd95b912-2aaa-11e6-944f-e87f9136b9bf.png) (red arrow like it is, blue like i see this :D)
Also loot window sometime bug and u cant move it 
![wowscrnshot_060416_231235](https://cloud.githubusercontent.com/assets/19752502/15801864/0d5bd96e-2aab-11e6-9475-c5fb04d8b522.jpg)

And this arrows for action bars nothing against it, but order for right I think ruined coz it first hides right bar 1 and only then 2.

If you are upset or insulted my english, I'm sorry. I really like your UI :D

**Comment by Kkthnx** [comment]
I am never insulted or upset by bug reports! I am thankful for you even using my UI. So thank you and I will look into these as soon as possible.

**Comment by Kkthnx** [comment]
Fix with update https://github.com/Kkthnx/KkthnxUI_WotLK/commit/e632bb1be5684c87c0f919c6145767de1e2660f7
