### ISSUE TITLE
Master Loot

### ISSUE THREAD

**Issue by Foximys** [Kkthnx/KkthnxUI_WotLK#38]
![wowscrnshot_061416_210743](https://cloud.githubusercontent.com/assets/3339049/16050644/e38766d0-3275-11e6-9e48-2293946eb6fe.jpg)

**Comment by Kkthnx** [comment]
Will look into this when I finish what I am working on currently. Thank you for this report.

Будет смотреть на это, когда я закончу то, что я работаю на данный момент. Благодарим Вас за этот доклад.

**Comment by Kkthnx** [comment]
Should be fixed with update https://github.com/Kkthnx/KkthnxUI_WotLK/commit/55b6aeac68bed99f8ae28ff602fe040acda64580
