### ISSUE TITLE
Skada skin.

### ISSUE THREAD

**Issue by freesay** [Kkthnx/KkthnxUI_WotLK#40]
I liked the skin Scada in your screenshot. But after applying /settings all  occurs problem:
![wowscrnshot_061716_192310](https://cloud.githubusercontent.com/assets/19500175/16157466/54563bbe-34c1-11e6-85bf-20f1ede622ac.jpg)
The addon does not move. Settings Icon is below. Lines look different than you.

**Comment by freesay** [comment]
Oh, sorry. I did not see it.
![wowscrnshot_061716_193311](https://cloud.githubusercontent.com/assets/19500175/16158556/553cf6e4-34c6-11e6-851e-04d383e5b4b9.jpg)
But anyway line look different.

**Comment by Kkthnx** [comment]
Fixed
