### ISSUE TITLE
Grid font.

### ISSUE THREAD

**Issue by freesay** [Kkthnx/KkthnxUI_WotLK#41]
![wowscrnshot_061716_200802](https://cloud.githubusercontent.com/assets/19500175/16158832/e6ba96fc-34c7-11e6-8ef5-4ac8c33fffe0.jpg)
Can you add support  font "Normal" from Grid?

**Comment by Kkthnx** [comment]
I can not reproduce this. 
![dwdwdq](https://cloud.githubusercontent.com/assets/1692977/16172709/c9709df0-355b-11e6-8dd3-cef68edfd299.PNG)
