### ISSUE TITLE
Something went wrong.

### ISSUE THREAD

**Issue by freesay** [Kkthnx/KkthnxUI_WotLK#44]
![wowscrnshot_061816_231212](https://cloud.githubusercontent.com/assets/19500175/16173436/3d6ddd96-35aa-11e6-9c19-1af60c7e8dda.jpg)
![wowscrnshot_061816_231210](https://cloud.githubusercontent.com/assets/19500175/16173456/89b883cc-35aa-11e6-9de4-a24f5f131885.jpg)

**Comment by Kkthnx** [comment]
This is meant to be. I just been lazy with all the changes I am doing. Ill go ahead and fix this though.

**Comment by freesay** [comment]
Hp and powerbar.
![wowscrnshot_061816_232645](https://cloud.githubusercontent.com/assets/19500175/16173533/418847ca-35ac-11e6-88eb-466a1dacd551.jpg)

**Comment by Kkthnx** [comment]
All fixed!
