### ISSUE TITLE
Not all.

### ISSUE THREAD

**Issue by freesay** [Kkthnx/KkthnxUI_WotLK#47]
Sorry, but you are not repaired all the bugs.
![wowscrnshot_061916_001644](https://cloud.githubusercontent.com/assets/19500175/16173744/ae391366-35b3-11e6-92b6-5409159771f2.jpg)

**Comment by Kkthnx** [comment]
those will be fixed later when I get back on I'm coveting  the setting and such and plan to reconstruct  the file system too so things are gonna messy for a couple weeks. the options will still work though.

**Comment by Kkthnx** [comment]
All issues should be resolved in commit https://github.com/Kkthnx/KkthnxUI_WotLK/commit/3776958fa59e6c29f4c245f4ed9a73989ece03a0

I also fixed the auto inv issue too.
