### ISSUE TITLE
Skin map.

### ISSUE THREAD

**Issue by freesay** [Kkthnx/KkthnxUI_WotLK#48]
![wowscrnshot_061916_062045](https://cloud.githubusercontent.com/assets/19500175/16174986/1189d0fe-35e6-11e6-98da-3cc5aeebce39.jpg)

**Comment by Kkthnx** [comment]
I am troubled with this issue with the text not displaying right! I will work on this.

**Comment by Kkthnx** [comment]
The map was recoded.
