### ISSUE TITLE
Bank is bug.

### ISSUE THREAD

**Issue by freesay** [Kkthnx/KkthnxUI_WotLK#52]
The bank does not open with last update.

**Comment by Kkthnx** [comment]
Fixed with https://github.com/Kkthnx/KkthnxUI_WotLK/commit/5062fcff20a46408d073022b551b79a0b0782fc5

**Comment by Kkthnx** [comment]
Also, there seems to be a sorting bug. I tried some changes and it happens less often but I'll have to look into it later.

Кроме того, там, кажется, сортировки ошибка. Я попробовал некоторые изменения, и это происходит реже, но я должен буду смотреть в него позже.
