### ISSUE TITLE
Missing some options.

### ISSUE THREAD

**Issue by freesay** [Kkthnx/KkthnxUI_WotLK#61]
Missing some options. It should be?

Before:
![1](https://cloud.githubusercontent.com/assets/19500175/16391209/ce6b13b2-3cae-11e6-95bc-7620f4bd1672.jpg)
After:
![2](https://cloud.githubusercontent.com/assets/19500175/16391219/d909f7c0-3cae-11e6-809a-f823d7eb2c54.jpg)

**Comment by Kkthnx** [comment]
This is part of the new Auras code. This is how it is so far.

Это часть нового кода Ауры. Вот как это до сих пор.
