### ISSUE TITLE
Buffs is strange.

### ISSUE THREAD

**Issue by freesay** [Kkthnx/KkthnxUI_WotLK#62]
![wowscrnshot_062716_220205](https://cloud.githubusercontent.com/assets/19500175/16392439/8d32dd98-3cb4-11e6-8ec3-2e7458993b13.jpg)
![wowscrnshot_062716_220638](https://cloud.githubusercontent.com/assets/19500175/16392443/9557567a-3cb4-11e6-94e7-d65fe59dbc5d.jpg)

**Comment by Kkthnx** [comment]
Okay, I finished the buffs up and fixed the issue you reported. Let me know what its like.

Хорошо, я закончил наложению и исправили проблему вы сообщили. Дайте мне знать, что его подобное.
