### ISSUE TITLE
Buttons & red errors.

### ISSUE THREAD

**Issue by freesay** [Kkthnx/KkthnxUI_WotLK#67]
Make addition checkbox to enable/disable the display of red errors.
Also strange look buttons with accessories.
![wowscrnshot_070516_203126](https://cloud.githubusercontent.com/assets/19500175/16602016/9254499a-4319-11e6-89bc-2481b04f7ae7.jpg)

**Comment by Kkthnx** [comment]
The buttons is kinda a test thingy right now. It shows green for what you have equipped. I just need to make it scale and fit properly once the player adjusts the size of their bars.

For the errors, I have an idea. I'll revert back to the old system I used and use the White / Blacklist system.

Кнопки любопытное тест штуковина прямо сейчас. Он показывает зеленый цвет для того, что вы есть. Мне просто нужно, чтобы сделать его масштабировать и соответствовать должным образом после того, как игрок регулирует размер их баров.

Для ошибок, у меня есть идея. Я вернуться к старой системе, которую я использовал и использовать систему / Черный список Белый.
