### ISSUE TITLE
Minimap issues

### ISSUE THREAD

**Issue by bottlehead** [Kkthnx/KkthnxUI_WotLK#74]
Hi.
When turning off the minimap in your UI options, a square formed minimap from your UI will clip with the default one. Also, on your minimap I can't access some things like Atlasloot button, or the tracking button, but it will always show the battleground/LFG inviter/bartender though. And I can't get the map to show time.

Really appreciate that you updated so fast to 7.0, thanks so much

**Comment by Kkthnx** [comment]
Is this a report for 7.0?

**Comment by Kkthnx** [comment]
If so please post it on the Legion version and I will work on it. I don't have access to game time currently.

**Comment by Kkthnx** [comment]
Fix https://github.com/Kkthnx/KkthnxUI_Legion/commit/64cc1d0af47e0733d9a94036aff19cbe30100c57

**Comment by bottlehead** [comment]
I meant to post it on your Legion version. The Issue Report on your Legion F.A.Q. links to https://github.com/Kkthnx/KkthnxUI-3.3.5/issues/new that's how it ended up here.

Thanks!

**Comment by Kkthnx** [comment]
Opps Ill get that fixed now!
